services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root      
    ports:
      - "3308:3306"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
  backend:
    build:
      context: ./
    ports:
      - "8088:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./config-backup:/backup   
  frontend:
    build:
      context: ../trans-react
    ports:
      - "3000:80"
    environment:
      - VITE_BE_API_URL=http://localhost:8088/api

networks:
  my-network:
    driver: bridge
volumes:
  config-backup:  

